service: spacenow-listings

dotenv:
  path: ./.env
  basePath: ./
  include:
    - POOL_ID
    - ACCOUNT_ID

custom:
  poolId: ${env:POOL_ID}
  accountId: ${env:ACCOUNT_ID}
  prune:
    automatic: true
    number: 3

provider:
  name: aws
  runtime: nodejs10.x

functions:
  - ${file(src/functions/authorize/authorize.yml)}
  - ${file(src/functions/listing.yml)}
  - ${file(src/functions/listing-photo.yml)}
  - ${file(src/functions/listing-category.yml)}
  - ${file(src/functions/listing-attribute.yml)}
  - ${file(src/functions/listing-access-day.yml)}
  - ${file(src/functions/listing-access-hour.yml)}

plugins:
  - serverless-offline
  - serverless-prune-plugin
  - serverless-dotenv-plugin

resources:
  - ${file(resources/api-gateway-errors.yml)}
